### ISSUE TITLE
not issuse. question.

### ISSUE THREAD

**Issue by gamidov-r** [ValvePython/vpk#1]
what about write files in vpk or create vpk from dir? only this normal work on linux (non-wine programs) with vpk 1.

**Comment by rossengeorgiev** [comment]
Currently neither are supported. I imagine such functionality will be added in a future version, but I can give any time-frame for that.

**Comment by gamidov-r** [comment]
Thank's!

**Comment by rossengeorgiev** [comment]
The module can now be used to create VPK from a directory.

**Comment by gamidov-r** [comment]
very good, big thank's!

**Comment by aakord** [comment]
It's possible/how to controll the version of the vpk generated?
vpk packages come in two different versions:
https://developer.valvesoftware.com/wiki/VPK_File_Format#Versions

**Comment by rossengeorgiev** [comment]
At moment only v1 can be created, but you can read v1 and v2.
