### ISSUE TITLE
Creating VPK from directory doesn't work on Linux

### ISSUE THREAD

**Issue by MaximDevoir** [ValvePython/vpk#14]
**Steps to Reproduce**

```bash
vpk --create /root/path/to/dir/ ./path/to/output.vpk
```

Results in:

```bash
Traceback (most recent call last):
  File "/home/maximdevoir/.pyenv/versions/3.7.3/bin/vpk", line 8, in <module>
    sys.exit(main())
  File "/home/maximdevoir/.pyenv/versions/3.7.3/lib/python3.7/site-packages/vpk/cli.py", line 182, in main
    create_vpk(args.create, args.file)
TypeError: create_vpk() takes 1 positional argument but 2 were given

```

**Environment Information**

VPK version: `1.3.0`
Python version: `Python 3.7.3`
OS: Ubuntu/Debian `18.04.3 LTS`

**Comment by MaximDevoir** [comment]
It looks like an old version is uploaded on PyPI.

**Comment by MaximDevoir** [comment]
@rossengeorgiev could you manually upload the new version?

**Comment by MaximDevoir** [comment]
In the meantime, for those that require the `create` function, you can install a git repository with `pip` by running:

```bash
pip install git+git://github.com/ValvePython/vpk.git
```

or

```bash
pip install git+https://github.com/ValvePython/vpk.git
```

**Comment by rossengeorgiev** [comment]
Hi @MaximDevoir, I will push a new release tonight. Thanks for the reminder
