### ISSUE TITLE
Bug: Can't read files from VPK

### ISSUE THREAD

**Issue by MrBean355** [ValvePython/vpk#16]
I'm unable to read nested files from a VPK.
This works:
```
pak1 = vpk.open("C:/Steam Library/steamapps/common/dota 2 beta/game/dota/pak01_dir.vpk")
pak1File = pak1["matchmodes.txt"]
print(pak1File.read().decode())
```
This does not work:
```
pak1 = vpk.open("C:/Steam Library/steamapps/common/dota 2 beta/game/dota/pak01_dir.vpk")
pak1File = pak1["resource/localization/abilities_english.txt"]
print(pak1File.read().decode())
```
It throws the error: `KeyError: "Path doesn't exist"`

Perhaps I'm doing something wrong?
Thanks for a great project!

**Comment by rossengeorgiev** [comment]
It tells you that there is no file with that path

**Comment by MrBean355** [comment]
There is though. I'm trying to read from the default `pak01_dir.vpk` file.
Is it because the file I'm looking for is in one of the `pak01_*.vpk` files?

**Comment by rossengeorgiev** [comment]
No. What I mean is, there is not such path (`resource/localization/abilities_english.txt`) in the VPK itself. You can also list the files by iterating over the `pak1File`. I don't remember, but the paths might be using backslashes.

**Comment by rossengeorgiev** [comment]
Looks like the use of `os.path.join` creates incorrect path with Python on Windows.
Offending line: https://github.com/ValvePython/vpk/blob/7f2cdf6bec28ca0d87a0ab1387a7dfd732fb962d/vpk/__init__.py#L410

**Comment by rossengeorgiev** [comment]
I think this has been fixed for good. Just update your `vpk` package. Let me know if there are issues

**Comment by MrBean355** [comment]
Thanks @rossengeorgiev, works well now! Appreciate your project.
