### ISSUE TITLE
Does not work with Insurgency

### ISSUE THREAD

**Issue by dieselburner** [ValvePython/vpk#17]
Listing files works. Extracting creates all directories, files with correct sizes, but they are empty (zeroed). Executing `vpk -t insurgency_misc_dir-original.vpk` gives following:

> ...
> scripts/bugreport_mapnumber.txt: FAILED
> scripts/bugreporter_defaults.txt: FAILED
> scripts/bonus_maps_manifest.txt: FAILED
> scripts/actremap.txt: FAILED
> scripts/actbusy.txt: FAILED

System info:

```
xxx:~/temp$ cat /etc/issue
Debian GNU/Linux 9 \n \l

xxx:~/temp$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)

xxx:~/temp$ vpk --version
vpk 1.3.2
```

Let me know how can I help you debugging this issue.

**Comment by dieselburner** [comment]
Ok, my bad. Apparently this works if executed from original `vpk` file location. Does not work if a single `vpk` file is copied to, e.g., `~/temp` dir, and extracted from there.

**Comment by rossengeorgiev** [comment]
I don't quite understand. The` _dir` file contains just the file metadata and structure. The contents of the files would be located in the similarly named `vpk` files going 01, 02, 03. You cannot point to them individually, as they contain no context as to what is inside. They all have to be together at the same location.
