### ISSUE TITLE
"File is not VPK" in csgo's vpk

### ISSUE THREAD

**Issue by 14NGiestas** [ValvePython/vpk#20]
```
$ vpk -l "/home/ian/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/pak01_000.vpk"
Error: File is not VPK (invalid magic)
```

**Comment by rossengeorgiev** [comment]
That file is only data, use `pak01_dir.vpk`.

**Comment by 14NGiestas** [comment]
Thanks. I think the error message should be changed in such cases. What kind of data those vpk contain?

**Comment by rossengeorgiev** [comment]
`_dir` contains metadata, the other files are just data. It's also possible have one file with metadata and data
