### ISSUE TITLE
Error loading vpk with dota2

### ISSUE THREAD

**Issue by mreak** [ValvePython/vpk#24]
I successfully packaged the official dota2 custom game-overthrow, but there are some errors.

Console Code
`dota_launch_custom_game overthrow_test test_1`

1. dota2 can't load the path of panorama code correctly.
`panorama:CSource2UIFileSystem:LoadFilelntoBuffer():Error loading panorama/layout/loading screen.xml c: Addons can only add layouts in the panoramalayout/custom gamel subdirector.`

2. It also fails to load when I add some custom assets(models/texture).

I really hope it can be fixed.Thank you

**Comment by rossengeorgiev** [comment]
Dota 2 probably only supports v2 VPK file. Since `v1.4.0` v2 is the default format.

Related #25
