### ISSUE TITLE
Documentation on the website is out of date

### ISSUE THREAD

**Issue by Alex-Bujorianu** [ValvePython/vpk#28]
Hello,

I don’t where else to post this, but the documentation available on: https://developer.valvesoftware.com/wiki/VPK#Linux_.2F_Unix does not reference this repository/tool. I wasted a lot of time setting up the shell script, only to find that it did not even work with Left 4 Dead 2 VPKs because it only produced VPK version 2 (or something like that). Could you please update that page with the recommendation to install Python `vpk` using `pip` instead?

**Comment by oxr463** [comment]
The developer wiki is an official resource from Valve, this GitHub organization and associated projects aren't. Perhaps you could try creating a wiki account and updating it?

**Comment by Alex-Bujorianu** [comment]
Oh… I didn’t even realise this repository was not maintained by Valve employees. Very well, I will make an account on the wiki.

**Comment by rossengeorgiev** [comment]
![image](https://user-images.githubusercontent.com/2720787/146040631-803d2234-d4d9-43d3-aea4-00b01c56469e.png)

The `vpk` cli tool referenced on the wiki, is not what is provided by this package
