### ISSUE TITLE
Creating VPKs containing materials does not work on Team Fortress 2

### ISSUE THREAD

**Issue by sticks-stuff** [ValvePython/vpk#29]
Console is also spammed with ` Material X does not support vertex format used by the mesh (maybe missing fields or mismatched vertex compression?), mesh will not be rendered. Grab a programmer!`

Attached is a demonstration of this bug. Included in the zip is the original folder used to generate the VPKs, a VPK generated from the folder using bin/vpk.exe (test_vpk_bin.vpk), and a VPK generated using this library (test_vpk_python.vpk). 
[test_vpk.zip](https://github.com/ValvePython/vpk/files/7772508/test_vpk.zip)

Putting either the original folder or test_vpk_bin.vpk in the tf/custom directory results in the Soldier's rocket launcher being edited (intentionally), however using test_vpk_python.vpk will result in the model being rendered invisible the console will be spammed with `Material models/weapons/c_models/c_rocketlauncher/c_rocketlauncher does not support vertex format used by the mesh (maybe missing fields or mismatched vertex compression?), mesh will not be rendered. Grab a programmer!` for as long as the model is on screen.

From my armchair perspective, it seems like its in the way this library encodes filenames (show in this comparison of the binaries), which seems to differ from the official tool. 
![image](https://user-images.githubusercontent.com/4157860/147314918-0e896e66-81f1-49ae-bb3b-af05b448d21e.png)

I have no idea though, just thought that might be useful to bring up

**Comment by sticks-stuff** [comment]
Nevermind, I'm just a dummy, TF2 uses VPK version 2 and this library only supports creating VPKs of version 1

**Comment by rossengeorgiev** [comment]
Added support for creating version 2 files, and made it default. Try that and let me know works

Related #25

**Comment by sticks-stuff** [comment]
Works perfectly, thank you so much!!
