### ISSUE TITLE
Maybe add a way to convert a vetx_c image to other formats ?

### ISSUE THREAD

**Issue by TimotheeJeannin** [ValvePython/vpk#4]
With the [ValveResourceFormat](https://github.com/SteamDatabase/ValveResourceFormat CLI) we can convert `vtex_c` images into `png` images. It would be great to be able to do this with this library.

**Comment by rossengeorgiev** [comment]
I like the idea. However that's outside of the scope for this package.

It's worth mentioning that VRS is written in C#, which doesn't play all that well with python
