### ISSUE TITLE
UnicodeDecodeError on non-ASCII filenames

### ISSUE THREAD

**Issue by nosoop** [ValvePython/vpk#6]
Hello!  I'm currently working on a project that deals with VPKs from the Workshop.

`_read_cstring` ([specifically here][]) fails when reading non-ASCII filenames.  An example Workshop entry is this [Back to School][bts] pack.  Valve's VPK utility lists one file that is rendered as the following in `less`:

`materials/vgui/maps/<D1><EE><E4><E5><F0><E6><E0><ED><E8><E5> onenote.onetoc2`

Most other VPKs in the sample I have do not run into this issue.

Not sure what the best approach for this is.

In any case, thanks for all the work on the library!

[specifically here]: https://github.com/ValvePython/vpk/blob/5fbf5e320d0538a12a6f1557617e486d2fa2993a/vpk/__init__.py#L402
[bts]: https://steamcommunity.com/sharedfiles/filedetails/?id=122453134

**Comment by rossengeorgiev** [comment]
Hi. Thanks for the report. Looks like VPK can contain extended ASCII characters. I'll push a fix now
