### ISSUE TITLE
Creating VPK from directory doesn't work on Windows

### ISSUE THREAD

**Issue by JCRPaquin** [ValvePython/vpk#8]
Looks like file paths are tripping up Windows. Specifically, I couldn't create a VPK given a directory on Windows under Python 3.6.

I've fixed it locally using `pathlib` but haven't tested on a *nix platform yet; will push these changes to a fork soon.

Using `pathlib` may cause issues with Python 2; I'm not sure how much this upsets you.

**Comment by rossengeorgiev** [comment]
Any stracktrace? Steps to reproduce?

**Comment by JCRPaquin** [comment]
Python 3.6.3, Windows 10

To reproduce:
1. Make a root folder
2. Make a subfolder
3. Add a file to the subfolder
4. Run `vpk -c <root folder name> <vpk name>`

The process should fail with an IOError indicating that no such file was found. No stack trace is output.

**Comment by rossengeorgiev** [comment]
Cool, I reproduced the issue.
